### PR TITLE
fix(procfile): get the procfile from the slug if not present

### LINKED ISSUE #213: Custom BUILDPACK_URL doesn't work
Deploying [example-perl](https://github.com/deis/example-perl) on current Deis v2 fails:
```console
$ cd example-perl
$ deis create --buildpack https://github.com/miyagawa/heroku-buildpack-perl.git
Creating Application... done, created guided-question
Git remote deis added
remote available at ssh://git@deis.192.168.64.2.xip.io:2222/guided-question.git
$ deis config
=== guided-question Config
BUILDPACK_URL      https://github.com/miyagawa/heroku-buildpack-perl.git
$ git push deis master
Counting objects: 41, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (36/36), done.
Writing objects: 100% (41/41), 11.10 KiB | 0 bytes/s, done.
Total 41 (delta 12), reused 0 (delta 0)
remote: 2016/03/01 04:03:39 Running in debug mode
Running git hook
read [0000000000000000000000000000000000000000,eaed0559111ca65588ec24897316faf8d9007a38,refs/heads/master]
Workflow request /v2/hooks/push (body elided)
Workflow request POST /v2/hooks/config
{"receive_user":"matt","receive_repo":"guided-question"}
got the following config back for app guided-question: {Owner:matt App:guided-question Values:map[BUILDPACK_URL:https://github.com/miyagawa/heroku-buildpack-perl.git] Memory:map[] CPU:map[] Tags:map[] UUID:9ec0e2aa-0598-44b5-8116-ef67b8b9e776 Created:2016-03-01 04:03:24 +0000 UTC Updated:2016-03-01 04:03:24 +0000 UTC}
found custom buildpack URL https://github.com/miyagawa/heroku-buildpack-perl.git
running [git archive --format=tar.gz --output=guided-question.tar.gz eaed0559] in directory /home/git/guided-question.git
remote: 2016/03/01 04:03:39 Error running git receive hook [reading /home/git/guided-question.git/build/tmp999357363/Procfile]
running [tar -xzf guided-question.tar.gz -C /home/git/guided-question.git/build/tmp999357363/] in directory /home/git/guided-question.git
To ssh://git@deis.192.168.64.2.xip.io:2222/guided-question.git
 * [new branch]      master -> master
```

### PR DESCRIPTION
**Pull request by kmala**
fixes #213

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -49,7 +49,6 @@ test:
 
 docker-build:
 	docker build --rm -t ${IMAGE} rootfs
-	perl -pi -e "s|image: [a-z0-9.:]+\/deis\/bp${SHORT_NAME}:[0-9a-z-.]+|image: ${IMAGE}|g" ${RC}
```
Comment (arschles) [inline Makefile]: :+1:

File: pkg/gitreceive/build.go [hunk 2]
```diff
@@ -237,6 +226,29 @@ func build(conf *Config, s3Client *storage.Client, kubeClient *client.Client, fs
...
+			rawProcFile, err := storage.DownloadObject(s3Client, conf.Bucket, slugBuilderInfo.AbsoluteProcfileKey())
+			if err != nil {
+				return fmt.Errorf("reading %s/%s", conf.Bucket, slugBuilderInfo.AbsoluteProcfileKey())
+			}
+			if err := yaml.Unmarshal(rawProcFile, &procType); err != nil {
+				return fmt.Errorf("procfile %s/%s is malformed (%s)", conf.Bucket, slugBuilderInfo.AbsoluteProcfileKey(), err)
+			}
+		}
+	}
+
```
Comment (arschles) [inline pkg/gitreceive/build.go]: Can you move this out into a separate `func` and write tests for it as well?

File: pkg/gitreceive/build.go [hunk 3]
```diff
@@ -237,6 +226,29 @@ func build(conf *Config, s3Client *storage.Client, kubeClient *client.Client, fs
...
+		if _, err := os.Stat(fmt.Sprintf("%s/Procfile", tmpDir)); err == nil {
+			rawProcFile, err := ioutil.ReadFile(fmt.Sprintf("%s/Procfile", tmpDir))
+			if err != nil {
+				return fmt.Errorf("reading %s/Procfile", tmpDir)
+			}
+			if err := yaml.Unmarshal(rawProcFile, &procType); err != nil {
+				return fmt.Errorf("procfile %s/ProcFile is malformed (%s)", tmpDir, err)
+			}
+		} else {
+			log.Info("Procfile not present. Getting it from the buildpack")
```
Comment (arschles) [inline pkg/gitreceive/build.go]: can you add a debug log under the info log, to indicate where we're getting the procfile from?

File: pkg/gitreceive/storage/object.go [hunk 4]
```diff
@@ -72,3 +73,16 @@ func WaitForObject(statter ObjectStatter, bucketName, objKey string, tick, timeo
...
+func DownloadObject(getter ObjectGetter, bucketName, objKey string) ([]byte, error) {
+	reader, err := getter.GetObject(bucketName, objKey)
+	if err == nil {
+		defer reader.Close()
+		if data, err := ioutil.ReadAll(reader); err != nil {
+			return nil, err
+		} else {
+			return data, err
+		}
+	}
```
Comment (arschles) [inline pkg/gitreceive/storage/object.go]: @kmala can you switch the boolean logic around, so that the `err != nil` logic is inside the `if`? It'll be more idiomatic that way.

**Comment by arschles** [comment]
@kmala can you please include some testing instructions here? Also I've added the beta milestone to this PR since #213 is under beta.

**Comment by kmala** [comment]
Testing:
Deploying [example-perl](https://github.com/deis/example-perl) should work fine after including these changes.

**Comment by mboersma** [comment]
Here's how I tested this change:

1. Build deis/slugbuilder#34 locally
2. Push that slugbuilder image to an accessible registry
3. Change the top of k8s_util.go in builder to reference that image, e.g.: `slugBuilderImage   = "quay.io/mboersma/slugbuilder:0.0.1-20160307153438"`
4. Build deis/builder#239 (this PR) along with the above change
5. Push that builder image to an accessible registry
6. Modify your deis-builder-rc.yaml to reference the builder image
7. Destroy and recreate the builder RC
8. Test as described in deis/builder#213.

**Comment by bacongobbler** [comment]
@kmala good to merge

**Comment by kmala** [comment]
@bacongobbler i am writing few unit test  for this as per @arschles suggestion.I will complete it in some time and then merge

File: pkg/gitreceive/build.go [hunk 5]
```diff
@@ -274,3 +272,26 @@ func prettyPrintJSON(data interface{}) (string, error) {
 	}
 	return string(formatted.Bytes()), nil
 }
+
+func getProcFile(getter storage.ObjectGetter, dirName, bucketName, procfileKey string) (pkg.ProcessType, error) {
+	procType := pkg.ProcessType{}
+	if _, err := os.Stat(fmt.Sprintf("%s/Procfile", dirName)); err == nil {
+		rawProcFile, err := ioutil.ReadFile(fmt.Sprintf("%s/Procfile", dirName))
+		if err != nil {
+			return nil, fmt.Errorf("reading %s/Procfile", dirName)
```
Comment (arschles) [inline pkg/gitreceive/build.go]: @kmala can you please include the original error at the end of this error string (as you do below)?

File: pkg/gitreceive/build_test.go [hunk 6]
```diff
@@ -0,0 +1,87 @@
...
+)
+
+func TestGetProcFileFromRepoSuccess(t *testing.T) {
+	tmpDir := os.TempDir()
+	data := []byte("web: example-go")
+	if err := ioutil.WriteFile(tmpDir+"/Procfile", data, 0644); err != nil {
+		t.Fatalf("error creating %s/Procfile (%s)", tmpDir, err)
+	}
+	defer func() {
+		if err := os.Remove(tmpDir + "/Procfile"); err != nil {
```
Comment (arschles) [inline pkg/gitreceive/build_test.go]: this is gonna leak the actual temporary directory itself. can you change this to `os.RemoveAll(tmpDir)` so that the dir also is removed? Same with the below test

File: pkg/gitreceive/build_test.go [hunk 7]
```diff
@@ -0,0 +1,87 @@
...
+	"github.com/deis/builder/pkg/gitreceive/storage"
+)
+
+const (
+	bucketName = "mybucket"
+	objKey     = "myobj"
+)
+
+func TestGetProcFileFromRepoSuccess(t *testing.T) {
+	tmpDir := os.TempDir()
```
Comment (arschles) [inline pkg/gitreceive/build_test.go]: I'd suggest [`ioutil.TempDir`](https://godoc.org/io/ioutil#TempDir) instead of `os.TempDir` here. `os.TempDir` returns the standard temp directory on the system, which is always the same, while `ioutil.TempDir` returns a new random directory under that standard dir

Comment (arschles) [inline pkg/gitreceive/build_test.go]: same with the below test

File: pkg/gitreceive/storage/interfaces.go [hunk 8]
```diff
@@ -79,3 +79,77 @@ func (f *FakeObjectPutter) PutObject(bucketName, objectKey string, reader io.Rea
...
+
+func (r *RealObjectGetter) GetObject(bucket, objKey string) (Object, error) {
+	obj, err := r.Client.GetObject(bucket, objKey)
+	if err != nil {
+		// you can return nil for an interface
+		return nil, err
+	}
+	// obj is a *s3.Object, but as we said above, it automatically implements our Object interface without any other work
+	return obj, nil
+}
```
Comment (arschles) [inline pkg/gitreceive/storage/interfaces.go]: A style note, (_not_ blocking for this PR):

Since `RealObjectGetter` is essentially a pass-through implementation to the Minio client's `GetObject` call, you can most likely make it non-exported and create a constructor `func` for it that returns an `ObjectGetter` interface.

Such code would look like this:

```go
type realObjectGetter struct {
  client *s3.Client
}

func (r *realObjectGetter) GetObject(bucket, objKey string) (Object, error) {
  ...
}

func NewRealObjectGetter(mcl *s3.Client) ObjectGetter {
  return &realObjectGetter{client: mcl}
}
```

File: pkg/gitreceive/storage/interfaces.go [hunk 9]
```diff
@@ -79,3 +79,77 @@ func (f *FakeObjectPutter) PutObject(bucketName, objectKey string, reader io.Rea
...
+	Calls []FakeGetObjectCall
+}
+
+// GetObject is the interface definition
+func (f *FakeObjectGetter) GetObject(bucketName, objectKey string) (Object, error) {
+	f.Calls = append(f.Calls, FakeGetObjectCall{BucketName: bucketName, ObjectKey: objectKey})
+	return f.Fn(bucketName, objectKey)
+}
+
+type FakeObject struct {
```
Comment (arschles) [inline pkg/gitreceive/storage/interfaces.go]: can you please add some documentation for this and its `func`s below?

File: pkg/gitreceive/build_test.go [hunk 10]
```diff
@@ -0,0 +1,93 @@
...
+const (
+	bucketName = "mybucket"
+	objKey     = "myobj"
+)
+
+func TestGetProcFileFromRepoSuccess(t *testing.T) {
+	tmpDir, err := ioutil.TempDir("", "tmpdir")
+	if err != nil {
+		t.Fatalf("error creating temp directory (%s)", err)
+	}
```
Comment (arschles) [inline pkg/gitreceive/build_test.go]: nitpick, but not blocking for this PR - you can shorten this next time to `assert.NoErr(t, err)`

**Comment by arschles** [comment]
@kmala LGTM3
