### PR TITLE
bug(builder): avoid simultaneous git push

### LINKED ISSUE #168: [Question]: Avoid simultaneous git push for the same application
In V1 this is not possible. I'm not sure if this should be allowed or not.
Running two simultaneous `git push` I see this in the builder logs:
```
Waiting for git-receive to run.
Waiting for deploy.
[info] Deploy complete.
[warning] Unreported error: error: Ref refs/heads/master is at 2bd4702d7ede8c417a0a070755e12b99ddbba6b7 but expected 0000000000000000000000000000000000000000
[info] Deploy complete.
```

### PR DESCRIPTION
**Pull request by aledbf**
```
$ git push deis master
fatal: remote error: Another git push is ongoing. Aborting...
exec request failed on channel 0
```

closes #168

### CODE REVIEW

**Comment by bacongobbler** [comment]
We should probably add unit tests for RepositoryLock

**Comment by aledbf** [comment]
@bacongobbler unit tests added

File: pkg/sshd/lock.go [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+
+// NewRepositoryLock returns a new instance of a key mutex.
+func NewRepositoryLock() RepositoryLock {
+	return &repoLock{
+		mutexMap: make(map[string]bool),
+	}
+}
+
+type repoLock struct {
+	sync.RWMutex
```
Comment (arschles) [inline pkg/sshd/lock.go]: can you give this a field name

File: pkg/sshd/lock.go [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+}
+
+// NewRepositoryLock returns a new instance of a key mutex.
+func NewRepositoryLock() RepositoryLock {
+	return &repoLock{
+		mutexMap: make(map[string]bool),
+	}
+}
+
+type repoLock struct {
```
Comment (arschles) [inline pkg/sshd/lock.go]: can you call this `inMemoryRepoLock`

File: pkg/sshd/lock.go [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+type RepositoryLock interface {
+	// Lock aquires a lock for a repository
+	Lock(repoName string) error
+	// Unlock releases the lock for a repository or returns
+	// an error if the specified name doesn't exist.
+	Unlock(repoName string) error
+}
+
+// NewRepositoryLock returns a new instance of a key mutex.
+func NewRepositoryLock() RepositoryLock {
```
Comment (arschles) [inline pkg/sshd/lock.go]: can you rename this `NewInMemoryRepositoryLock`?

File: pkg/sshd/lock.go [hunk 4]
```diff
@@ -0,0 +1,67 @@
...
+}
+
+type repoLock struct {
+	sync.RWMutex
+	mutexMap map[string]bool
+}
+
+// Lock aquires a lock associated with the specified name
+func (rl *repoLock) Lock(repoName string) error {
+	rl.RWMutex.Lock()
```
Comment (arschles) [inline pkg/sshd/lock.go]: it should be enough to `RLock` this if it's just for accessing the map, no?

File: pkg/sshd/lock.go [hunk 5]
```diff
@@ -0,0 +1,67 @@
...
+// NewRepositoryLock returns a new instance of a key mutex.
+func NewRepositoryLock() RepositoryLock {
+	return &repoLock{
+		mutexMap: make(map[string]bool),
+	}
+}
+
+type repoLock struct {
+	sync.RWMutex
+	mutexMap map[string]bool
```
Comment (arschles) [inline pkg/sshd/lock.go]: shouldn't this map from `string` to `*sync.Mutex`, so that you can lock each repo individually?

File: rootfs/Dockerfile [hunk 6]
```diff
@@ -11,6 +11,10 @@ RUN apk add --update-cache \
   xz \
   && rm -rf /var/cache/apk/*
 
+# install git and configure gituser
+ENV GITHOME /home/git
+ENV GITUSER git
```
Comment (arschles) [inline rootfs/Dockerfile]: :+1: - I ran into this in my PR as well

File: pkg/sshd/lock.go (hunk 4 above)
Comment (aledbf) [inline pkg/sshd/lock.go]: no because that produces a data race (I tried your suggestion using `go test -race -cover lock.go lock_test.go`)

Comment (arschles) [inline pkg/sshd/lock.go]: @aledbf I think that's because you're changing the `bool` values of `mutexMap`. See my comment at https://github.com/deis/builder/pull/170#discussion_r52618236 regarding changing the `bool` to a `*sync.Mutex`

File: pkg/sshd/lock.go [hunk 7]
```diff
@@ -0,0 +1,68 @@
...
+import (
+	"fmt"
+	"sync"
+)
+
+// RepositoryLock interface that allows the creation of a lock associated
+// with a repository name to avoid simultaneous git operations
+type RepositoryLock interface {
+	// Lock aquires a lock for a repository
+	Lock(repoName string) error
```
Comment (arschles) [inline pkg/sshd/lock.go]: @aledbf can this and `Unlock` below also accept a `timeout time.Duration`, so that thie future implementations can wait to acquire the lock

Comment (aledbf) [inline pkg/sshd/lock.go]: @arschles I tried that but it feels awkward see a git push just waiting. The behavior in this PR provides the same UX than in deis V1

Comment (arschles) [inline pkg/sshd/lock.go]: @aledbf I think for now we could solve that by passing `time.Duration(0)` to the `Lock` func.

If we use a network-based lock in the future, though, we're going to need to account for network delays, failure cases, etc... and a timeout is a simple first solution for doing so.

Comment (arschles) [inline pkg/sshd/lock.go]: Also, @aledbf - if / when we do decide to use a timeout greater than 0, we could still provide a progress indicator in the console - I wouldn't be opposed to that.

**Comment by arschles** [comment]
@aledbf how did you test this?

File: pkg/sshd/lock.go [hunk 8]
```diff
@@ -0,0 +1,63 @@
...
+}
+
+// Lock aquires a lock associated with the specified name
+func (rl *inMemoryRepoLock) Lock(repoName string, timeout time.Duration) error {
+	rl.mutex.Lock()
+	defer rl.mutex.Unlock()
+
+	_, exists := rl.dataMap[repoName]
+	if !exists {
+		fmt.Printf("Creating lock for repository %v\n", repoName)
```
Comment (arschles) [inline pkg/sshd/lock.go]: I don't think this should log here

File: pkg/sshd/lock.go [hunk 9]
```diff
@@ -0,0 +1,63 @@
...
+// with a repository name to avoid simultaneous git operations
+type RepositoryLock interface {
+	// Lock aquires a lock for a repository
+	Lock(repoName string, timeout time.Duration) error
+	// Unlock releases the lock for a repository or returns
+	// an error if the specified name doesn't exist.
+	Unlock(repoName string, timeout time.Duration) error
+}
+
+// NewInMemoryRepositoryLock returns a new instance of a key mutex.
```
Comment (arschles) [inline pkg/sshd/lock.go]: These docs don't seem to be current. What is a "key mutex". Also, it appears that the timeouts aren't respected here - can you add some docs to indicate that fact?

**Comment by aledbf** [comment]
@arschles executing simultaneous `git push` in the same app and `git push` in the middle of the build.

File: pkg/sshd/lock.go (hunk 9 above)
Comment (arschles) [inline pkg/sshd/lock.go]: Also, is it by design that the in memory mutex doesn't respect the timeout?

**Comment by arschles** [comment]
ok, thanks

**Comment by arschles** [comment]
also, would it be possible to add some tests for locking in `pkg/sshd/server_test.go`?

File: pkg/sshd/lock.go (hunk 8 above)
Comment (bacongobbler) [inline pkg/sshd/lock.go]: or at the very least we could keep this, but punt it to debug level

**Comment by arschles** [comment]
@aledbf tested and this works for me as well. let me know when you'd like another review

File: pkg/sshd/server.go [hunk 10]
```diff
@@ -215,6 +223,19 @@ func (s *server) answer(channel ssh.Channel, requests <-chan *ssh.Request, sshCo
 					req.Reply(ok, nil)
 					break
 				}
+
+				repoName := parts[1]
```
Comment (arschles) [inline pkg/sshd/server.go]: can you ensure that `len(parts) >= 2`. I know that it should in the common case, but it would be good to be defensive

File: pkg/sshd/lock_test.go [hunk 11]
```diff
@@ -0,0 +1,85 @@
...
+		t.Fatalf("unexpected error %v", err)
+	}
+}
+
+func TestInvalidUnlock(t *testing.T) {
+	rl := NewInMemoryRepositoryLock()
+	key := "fakeid"
+	err := rl.Unlock(key, time.Duration(0))
+	if err == nil {
+		t.Fatalf("expected error but returned nil", err)
```
Comment (arschles) [inline pkg/sshd/lock_test.go]: this fails `go vet`: `no formatting directive in Fatalf call` I think this can remove the `err` (since it's nil) and make this a `t.Fatal`

File: pkg/sshd/server.go (hunk 10 above)
Comment (aledbf) [inline pkg/sshd/server.go]: @arschles that was already present here https://github.com/deis/builder/pull/170#discussion-diff-53344595R221

Comment (arschles) [inline pkg/sshd/server.go]: k. sorry, I should have read up

**Comment by arschles** [comment]
@aledbf thanks for adding the additional test. I'm marking LGTM pending CI passing
